Repository UReverse-EarthGuard/UReverse-FE-member, pull requests merged in 2025-06, with the labels that each got.

#30 [Feat] 마이페이지 홈 레이아웃 및 판매 상태 트래킹 카드 구현
  package-lock.json
  src/App.js
  src/Root.module.css
  src/api/home.js
  src/assets/icon-arrow.png
  src/assets/icon-logout.png
  src/assets/icon-notification-bell.png
  src/assets/icon-settings.png
  src/component/button/HoverEventButton.jsx
  src/component/button/HoverEventButton.module.css
  src/component/card/StatCard.jsx
  src/component/card/StatCard.module.css
  src/component/card/TrackingCard.jsx
  src/component/card/TrackingCard.module.css
  src/component/header/MainHeader.jsx
  src/component/header/MainHeader.module.css
  src/component/landing/MainVisualSection.jsx
  src/component/landing/StartNowSection.jsx
  src/component/landing/StartNowSection.module.css
  src/pages/Home.jsx
  src/pages/Home.module.css
  src/pages/LandingPage.jsx
  src/pages/LandingPage.module.css
  src/pages/auth/LoginForm.jsx
  src/pages/auth/LoginForm.module.css
  src/pages/mypage/MyPageHome.jsx
Labels: ✨feat, 🐤 윤소정

#31 [Feat] notification SSE 단방향 알림 구현
  src/api/member.js
  src/component/icon/NotificationIcon.jsx
  src/component/mypage/notification/NotificationItem.jsx
  src/component/mypage/notification/NotificationItem.module.css
  src/component/sell/product/ProductInfo.jsx
  src/pages/notification/NotificationPage.jsx
  src/util/ConnectSSE.js
Labels: ✨feat, 박찬혁

#32 [Feat] 회원가입 및 비밀번호 재발급 UI 리디자인
  src/App.js
  src/component/header/MainHeader.jsx
  src/component/header/NoAlarmHeader.jsx
  src/component/modal/InfoModal.jsx
  src/component/modal/InfoModal.module.css
  src/pages/Home.jsx
  src/pages/auth/LoginForm.jsx
  src/pages/auth/LoginSelect.jsx
  src/pages/auth/RecoveryPasswordPage.jsx
  src/pages/auth/SignupForm.jsx
  src/pages/auth/SignupForm.module.css
Labels: ✨feat, 🐤 윤소정

#33 [Refactor] sign-up에서 signup으로 재변경
  src/App.js
  src/component/header/NoAlarmHeader.jsx
  src/pages/auth/LoginForm.jsx
  src/pages/auth/LoginSelect.jsx
Labels: 🐤 윤소정

#35 [Feat] 회원 정보 수정 페이지 레이아웃 개선 및 정보 유지 처리
  src/component/card/TrackingCard.jsx
  src/component/card/TrackingCard.module.css
  src/component/header/MainHeader.module.css
  src/component/icon/NotificationIcon.module.css
  src/component/modal/InfoModal.module.css
  src/component/modal/MessageModal.module.css
  src/pages/Home.module.css
  src/pages/auth/RecoveryPasswordPage.jsx
  src/pages/mypage/EditInfo.jsx
  src/pages/mypage/EditInfo.module.css
Labels: ✨feat, 🐤 윤소정

#39 [Feat] 로그인 후 접근 제어
  src/component/header/MainHeader.jsx
Labels: ✨feat, 🐤 윤소정

#42 [Fix] 회원가입 후, 로그인 화면 경로 재설정
  src/pages/auth/SignupForm.jsx
Labels: 🐤 윤소정, 🩹 fix

#53 Feat/api 001 notification 알림 아이콘 메세지 개수 실시간 반영
  src/App.js
  src/api/setupSSE.js
  src/component/icon/NotificationIcon.jsx
Labels: 🩹 fix
